output_dir: "results"
seed: 10
task: "REDDIT"
dryrun: False
save_prompts: True
timeout: 0.0
task_config: 
    path: "data/synthetic/synthetic_dataset.jsonl"
    outpath: "predicted_synthethic_gpt4.jsonl"
    profile_filter:
      hardness: 1
      certainty: 1
      num_tokens: 3000
    eval: False
gen_model:
  name: "deepseek-ai/DeepSeek-V3"
  provider: "openai"
  args: {
    temperature: 0.1
  }
